Repository okkur/syna, pull requests merged in 2018-09, with the labels that each got.

#330 Fix image width in content fragment
  layouts/partials/fragments/content.html
  static-main/styles/_syna.scss
  static/syna-main.css
Labels: enhancement

#315 Fix fragments lookup strategy
  exampleSite/content/dev/list/_index.md
  exampleSite/content/dev/list/_index/branches-header.md
  exampleSite/content/dev/list/_index/branches.md
  exampleSite/content/dev/list/_index/index.md
  exampleSite/content/dev/list/_index/leaves-header.md
  exampleSite/content/dev/list/_index/leaves.md
  exampleSite/content/dev/list/_index/upper-leaves-header.md
  exampleSite/content/dev/list/_index/upper-leaves.md
  exampleSite/content/dev/list/page-1/index.md
  exampleSite/content/dev/list/page-2/index.md
  exampleSite/content/dev/list/section-1/_index.md
  exampleSite/content/dev/list/section-1/page-1/index.md
  exampleSite/content/dev/list/section-1/page-2/index.md
  exampleSite/content/dev/list/section-2/_index.md
  exampleSite/content/dev/list/section-2/page-1/index.md
  exampleSite/content/dev/list/section-2/page-2/index.md
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/partials/fragments/list.html
  layouts/partials/helpers/fragments.html
  layouts/partials/helpers/image.html
Labels: enhancement

#331 Display category and date of the pages in list and content fragments
  exampleSite/content/dev/blog/_global/contact.md
  exampleSite/content/dev/blog/_global/index.md
  exampleSite/content/dev/blog/_index.md
  exampleSite/content/dev/blog/_index/contact.md
  exampleSite/content/dev/blog/_index/index.md
  exampleSite/content/dev/blog/_index/list.md
  exampleSite/content/dev/blog/article-1/index.md
  exampleSite/content/dev/blog/article-2/index.md
  exampleSite/content/dev/blog/article-2/screenshot.png
  exampleSite/content/dev/blog/article-3/index.md
  exampleSite/content/fragments/_index/list.md
  layouts/partials/fragments/content.html
  layouts/partials/fragments/list.html
  layouts/partials/helpers/categories.html
  layouts/partials/helpers/publish-date.html
Labels: enhancement

#337 Create list fragment example
  exampleSite/content/fragments/list/code-list-tiled.md
  exampleSite/content/fragments/list/code-list.md
  exampleSite/content/fragments/list/index.md
  exampleSite/content/fragments/list/list-tiled.md
  exampleSite/content/fragments/list/list.md
Labels: documentation

#327 Create search fragment
  exampleSite/config.toml
  exampleSite/content/_global/nav.md
  exampleSite/content/fragments/nav/code-nav-example.md
  exampleSite/content/fragments/nav/nav-example.md
  exampleSite/content/fragments/search/code-search.md
  exampleSite/content/fragments/search/index.md
  exampleSite/content/fragments/search/search.md
  exampleSite/content/search/index.md
  layouts/_default/index.json
  layouts/partials/fragments/nav.html
  layouts/partials/fragments/search.html
  layouts/partials/head.html
  layouts/partials/helpers/search-result-template.html
  package.json
  static-main/js/helpers/jq-helpers.js
  static-main/js/search.js
  static-main/styles/_header.scss
  static-main/styles/_search.scss
  static-main/styles/index.scss
  static/syna-contact.js
  static/syna-main.css
  static/syna-main.js
  static/syna-portfolio.js
  static/syna-search.js
  webpack.config.js
  yarn.lock
Labels: enhancement

#339 Fix background and text color of search in search and nav fragments
  exampleSite/content/fragments/list/code-list-tiled.md
  exampleSite/content/fragments/list/code-list.md
  exampleSite/content/fragments/list/list-tiled.md
  exampleSite/content/fragments/list/list.md
  exampleSite/content/fragments/search/search.md
  layouts/partials/fragments/nav.html
  layouts/partials/fragments/search.html
  layouts/partials/helpers/search-result-template.html
  static-main/styles/_search.scss
  static/syna-main.css
Labels: enhancement

#342 Update CHANGELOG for v0.13.0
  CHANGELOG.md
Labels: documentation

#347 Fix content fragment sidebar content breaking layout if string is too long
  layouts/partials/fragments/content.html
  static-main/styles/_syna.scss
  static/syna-main.css
Labels: bug

#349 Add minify flag to build commands
  netlify.toml
  package.json
Labels: enhancement

#354 Fix several regressions
  exampleSite/content/fragments/list/index.md
  layouts/partials/fragments/content.html
  layouts/partials/fragments/nav.html
  layouts/partials/helpers/categories.html
  layouts/partials/helpers/image.html
  layouts/partials/helpers/publish-date.html
Labels: bug

#328 Add support for pagination
  exampleSite/config.toml
  exampleSite/content/dev/list/_index/branches.md
  exampleSite/content/dev/list/_index/leaves.md
  exampleSite/content/dev/list/_index/upper-leaves.md
  layouts/partials/fragments/list.html
  layouts/partials/helpers/pagination.html
Labels: enhancement

#341 Add features section to the home page
  exampleSite/content/_index/items-1/configurable.md
  exampleSite/content/_index/items-1/fragments.md
  exampleSite/content/_index/items-1/index.md
  exampleSite/content/_index/items-1/react.md
  exampleSite/content/_index/items-2/customizable.md
  exampleSite/content/_index/items-2/extensible.md
  exampleSite/content/_index/items-2/index.md
  exampleSite/content/_index/list.md
Labels: enhancement

#356 Fix http scripts not loading
  layouts/partials/js.html
Labels: bug

#358 Fix issues within homepage
  exampleSite/content/_index/features-2/customizable.md
  exampleSite/content/_index/features-2/extensible.md
  exampleSite/content/_index/features-2/index.md
  exampleSite/content/_index/features/configurable.md
  exampleSite/content/_index/features/fragments.md
  exampleSite/content/_index/features/index.md
  exampleSite/content/_index/features/react.md
  exampleSite/content/_index/fragments.md
  exampleSite/content/_index/hero/index.md
  exampleSite/content/_index/list.md
Labels: bug

#319 Add bootstrap unresponsive grid to head of every page
  exampleSite/static/syna-grid.css
  layouts/partials/fragments/copyright.html
  layouts/partials/head.html
Labels: enhancement, revisit

#368 Fix url in pricing fragment
  layouts/partials/fragments/pricing.html
Labels: bug

#367 Fix order of fragments in pricing fragment example
  exampleSite/content/fragments/pricing/code-pricing.md
  exampleSite/content/fragments/pricing/pricing/index.md
Labels: bug

#366 Extract title and subtitle to a helper where possible
  layouts/partials/fragments/buttons.html
  layouts/partials/fragments/contact.html
  layouts/partials/fragments/content.html
  layouts/partials/fragments/embed.html
  layouts/partials/fragments/header.html
  layouts/partials/fragments/items.html
  layouts/partials/fragments/list.html
  layouts/partials/fragments/member.html
  layouts/partials/fragments/portfolio.html
  layouts/partials/fragments/pricing.html
  layouts/partials/fragments/search.html
  layouts/partials/fragments/table.html
  layouts/partials/helpers/section-header.html
Labels: refactor

#369 Fix random issues with fragments using subpath
  exampleSite/content/dev/empty-subitems/pricing/index.md
  exampleSite/content/fragments/items/code-items-no-content.md
  exampleSite/content/fragments/items/code-items-only.md
  exampleSite/content/fragments/items/code-items.md
  exampleSite/content/fragments/items/code-logos-no-content.md
  exampleSite/content/fragments/items/code-logos-only.md
  exampleSite/content/fragments/items/code-logos.md
  exampleSite/content/fragments/member/code-members.md
  exampleSite/content/fragments/member/code-single-member.md
  exampleSite/content/fragments/portfolio/code-portfolio.md
  exampleSite/content/fragments/pricing/code-pricing.md
  layouts/partials/fragments/pricing.html
  layouts/partials/helpers/empty-subpath.html
Labels: bug, documentation, enhancement

#370 Add alignment support to header helper
  exampleSite/content/fragments/buttons/buttons.md
  exampleSite/content/fragments/buttons/code-buttons.md
  exampleSite/content/fragments/contact/code-contact.md
  exampleSite/content/fragments/contact/contact.md
  exampleSite/content/fragments/content/code-content-sidebar-right.md
  exampleSite/content/fragments/content/code-content-sidebar.md
  exampleSite/content/fragments/content/code-content.md
  exampleSite/content/fragments/content/content-sidebar-right.md
  exampleSite/content/fragments/content/content-sidebar.md
  exampleSite/content/fragments/content/content.md
  exampleSite/content/fragments/embed/code-embed_subscribe.md
  exampleSite/content/fragments/embed/code-embed_video.md
  exampleSite/content/fragments/embed/embed_subscribe.md
  exampleSite/content/fragments/embed/embed_video.md
  exampleSite/content/fragments/header/code-header.md
  exampleSite/content/fragments/header/header.md
  exampleSite/content/fragments/items/code-items-no-content.md
  exampleSite/content/fragments/items/code-items-only.md
  exampleSite/content/fragments/items/code-items.md
  exampleSite/content/fragments/items/code-logos-no-content.md
  exampleSite/content/fragments/items/code-logos-only.md
  exampleSite/content/fragments/items/code-logos.md
  exampleSite/content/fragments/items/items-no-content/index.md
  exampleSite/content/fragments/items/items-only/index.md
  exampleSite/content/fragments/items/items/index.md
  exampleSite/content/fragments/items/logos-no-content/index.md
  exampleSite/content/fragments/items/logos-only/index.md
  exampleSite/content/fragments/items/logos/index.md
  exampleSite/content/fragments/list/code-list-tiled.md
  exampleSite/content/fragments/list/code-list.md
  exampleSite/content/fragments/list/list-tiled.md
  exampleSite/content/fragments/list/list.md
  exampleSite/content/fragments/member/code-members.md
  exampleSite/content/fragments/member/code-single-member.md
  exampleSite/content/fragments/member/members/index.md
  exampleSite/content/fragments/member/single-member/index.md
  exampleSite/content/fragments/portfolio/code-portfolio.md
  exampleSite/content/fragments/portfolio/portfolio/index.md
  exampleSite/content/fragments/pricing/code-pricing.md
  exampleSite/content/fragments/pricing/pricing/index.md
  exampleSite/content/fragments/search/code-search.md
  exampleSite/content/fragments/search/search.md
  exampleSite/content/fragments/table/code-table.md
  exampleSite/content/fragments/table/table.md
  layouts/partials/fragments/pricing.html
  layouts/partials/fragments/search.html
  layouts/partials/helpers/section-header.html
Labels: enhancement

#375 Add missing scratch to pagination helper call
  layouts/partials/fragments/list.html
Labels: bug

#382 Add breadcrumbs support to nav fragment
  exampleSite/content/_global/nav.md
  exampleSite/content/fragments/nav/nav-example.md
  layouts/partials/fragments/nav.html
  layouts/partials/helpers/fragments.html
Labels: enhancement

#384 Fix missing weight and not-properly-built files
  exampleSite/content/dev/contact/index.md
  exampleSite/content/dev/resource-fallthrough/_index/list.md
  exampleSite/resources/_gen/assets/js/scripts/syna-editor.js_d11fe7b62c27961c87ecd0f2490357b9.content
  exampleSite/resources/_gen/assets/js/scripts/syna-editor.js_d11fe7b62c27961c87ecd0f2490357b9.json
  exampleSite/resources/_gen/assets/js/scripts/syna-react.js_d11fe7b62c27961c87ecd0f2490357b9.content
  exampleSite/resources/_gen/assets/js/scripts/syna-react.js_d11fe7b62c27961c87ecd0f2490357b9.json
Labels: bug

#378 Fix some issues with list fragment
  layouts/partials/fragments/list.html
  layouts/partials/helpers/categories.html
  layouts/partials/helpers/publish-date.html
Labels: enhancement

#383 Fix fragments lookup order
  exampleSite/content/dev/fragment-fallthrough/_global/content.md
  exampleSite/content/dev/fragment-fallthrough/_global/copyright.md
  exampleSite/content/dev/fragment-fallthrough/_global/hero/header.jpg
  exampleSite/content/dev/fragment-fallthrough/_global/hero/index.md
  exampleSite/content/dev/fragment-fallthrough/_global/hero/logo.svg
  exampleSite/content/dev/fragment-fallthrough/_global/index.md
  exampleSite/content/dev/fragment-fallthrough/_index.md
  exampleSite/content/dev/fragment-fallthrough/_index/content.md
  exampleSite/content/dev/fragment-fallthrough/_index/footer.md
  exampleSite/content/dev/fragment-fallthrough/_index/hero/header.jpg
  exampleSite/content/dev/fragment-fallthrough/_index/hero/index.md
  exampleSite/content/dev/fragment-fallthrough/_index/hero/logo.svg
  exampleSite/content/dev/fragment-fallthrough/_index/index.md
  layouts/partials/helpers/fragments.html
Labels: bug
