Repository okkur/syna, pull requests merged in 2018-10, with the labels that each got.

#392 Fix content fragment images max-width
  layouts/partials/fragments/content.html
Labels: bug

#391 Fix date format messing up date
  layouts/partials/helpers/publish-date.html
Labels: bug

#393 Add support for frontmatter summary in content fragment for list fragment
  exampleSite/content/dev/blog/article-1/index.md
  layouts/partials/fragments/list.html
Labels: enhancement

#395 Remove nesting page
  exampleSite/content/nesting/content.md
  exampleSite/content/nesting/index.md
Labels: refactor

#396 Fix netlify form support
  layouts/partials/fragments/contact.html
Labels: bug

#404 Change global colors configuration
  assets/styles/index.scss
  exampleSite/config.toml
Labels: refactor

#405 Update build files
  assets/scripts/syna-editor.js
  assets/scripts/syna-react.js
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.content
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.json
Labels: bug

#406 Create new graph fragment
  assets/js/graph.js
  assets/scripts/syna-graph.js
  exampleSite/content/fragments/graph/code-stats.md
  exampleSite/content/fragments/graph/graph/config.json
  exampleSite/content/fragments/graph/graph/index.md
  exampleSite/content/fragments/graph/index.md
  exampleSite/resources/_gen/assets/js/scripts/syna-editor.js_d11fe7b62c27961c87ecd0f2490357b9.content
  exampleSite/resources/_gen/assets/js/scripts/syna-editor.js_d11fe7b62c27961c87ecd0f2490357b9.json
  exampleSite/resources/_gen/assets/js/scripts/syna-graph.js_d11fe7b62c27961c87ecd0f2490357b9.content
  exampleSite/resources/_gen/assets/js/scripts/syna-graph.js_d11fe7b62c27961c87ecd0f2490357b9.json
  exampleSite/resources/_gen/assets/js/scripts/syna-react.js_d11fe7b62c27961c87ecd0f2490357b9.content
  exampleSite/resources/_gen/assets/js/scripts/syna-react.js_d11fe7b62c27961c87ecd0f2490357b9.json
  exampleSite/resources/_gen/assets/js/scripts/syna-stats.js_d11fe7b62c27961c87ecd0f2490357b9.content
  exampleSite/resources/_gen/assets/js/scripts/syna-stats.js_d11fe7b62c27961c87ecd0f2490357b9.json
  layouts/partials/fragments/graph.html
  package.json
  webpack.config.js
  yarn.lock
Labels: enhancement

#410 Fix contact form
  layouts/partials/fragments/contact.html
Labels: bug

#394 Enable slots (fragment in fragment)
  exampleSite/config.toml
  exampleSite/content/dev/blog/_global/sidebar-header.md
  exampleSite/content/dev/blog/_global/sidebar-list.md
  exampleSite/content/dev/blog/article-1/index.md
  exampleSite/content/dev/blog/article-2/index.md
  exampleSite/content/dev/blog/article-3/index.md
  layouts/partials/fragments/buttons.html
  layouts/partials/fragments/contact.html
  layouts/partials/fragments/content.html
  layouts/partials/fragments/embed.html
  layouts/partials/fragments/faq.html
  layouts/partials/fragments/footer.html
  layouts/partials/fragments/graph.html
  layouts/partials/fragments/header.html
  layouts/partials/fragments/hero.html
  layouts/partials/fragments/item.html
  layouts/partials/fragments/items.html
  layouts/partials/fragments/list.html
  layouts/partials/fragments/member.html
  layouts/partials/fragments/portfolio.html
  layouts/partials/fragments/pricing.html
  layouts/partials/fragments/search.html
  layouts/partials/fragments/table.html
  layouts/partials/helpers/container.html
  layouts/partials/helpers/deprecation-warning.html
  layouts/partials/helpers/fragments-renderer.html
  layouts/partials/helpers/fragments.html
  layouts/partials/helpers/slot.html
Labels: enhancement, refactor

#414 WIP: Docs/global/document global variables
  assets/styles/_toc.scss
  assets/styles/index.scss
  docs/README.md
  exampleSite/config.toml
  exampleSite/content/docs/_global/content-toc.md
  exampleSite/content/docs/_global/index.md
  exampleSite/content/docs/_global/sidebar.md
  exampleSite/content/docs/_global/toc.md
  exampleSite/content/docs/_index.md
  exampleSite/content/docs/_index/content.md
  exampleSite/content/docs/_index/index.md
  exampleSite/content/docs/deployment/content.md
  exampleSite/content/docs/deployment/index.md
  exampleSite/content/docs/development/content.md
  exampleSite/content/docs/development/index.md
  exampleSite/content/docs/fragments-implementation/content.md
  exampleSite/content/docs/fragments-implementation/fragments-01.png
  exampleSite/content/docs/fragments-implementation/index.md
  exampleSite/content/docs/fragments/content.md
  exampleSite/content/docs/fragments/index.md
  exampleSite/content/docs/global-variables/content.md
  exampleSite/content/docs/global-variables/index.md
  exampleSite/content/docs/image-fallthrough/content.md
  exampleSite/content/docs/image-fallthrough/index.md
  exampleSite/content/docs/installation/content.md
  exampleSite/content/docs/installation/index.md
  exampleSite/content/docs/supported-colors/content.md
  exampleSite/content/docs/supported-colors/index.md
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.content
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.json
  layouts/partials/fragments/content.html
  layouts/partials/fragments/list.html
  layouts/partials/fragments/toc.html
Labels: documentation, refactor

#417 Add new text-black and text-white and use the for text color helper
  layouts/partials/helpers/text-color.html
Labels: enhancement

#418 Make list fragment collapsible by a variable
  assets/js/collapse.js
  assets/scripts/syna-collapse.js
  assets/scripts/syna-editor.js
  assets/scripts/syna-graph.js
  assets/scripts/syna-react.js
  assets/styles/_faq.scss
  assets/styles/_syna.scss
  assets/styles/_toc.scss
  exampleSite/content/docs/_global/sidebar.md
  exampleSite/content/fragments/list/code-list-tiled.md
  exampleSite/content/fragments/list/code-list.md
  exampleSite/content/fragments/list/list-tiled.md
  exampleSite/content/fragments/list/list.md
  exampleSite/resources/_gen/assets/js/scripts/syna-collapse.js_d11fe7b62c27961c87ecd0f2490357b9.content
  exampleSite/resources/_gen/assets/js/scripts/syna-collapse.js_d11fe7b62c27961c87ecd0f2490357b9.json
  exampleSite/resources/_gen/assets/js/scripts/syna-editor.js_d11fe7b62c27961c87ecd0f2490357b9.content
  exampleSite/resources/_gen/assets/js/scripts/syna-editor.js_d11fe7b62c27961c87ecd0f2490357b9.json
  exampleSite/resources/_gen/assets/js/scripts/syna-graph.js_d11fe7b62c27961c87ecd0f2490357b9.content
  exampleSite/resources/_gen/assets/js/scripts/syna-graph.js_d11fe7b62c27961c87ecd0f2490357b9.json
  exampleSite/resources/_gen/assets/js/scripts/syna-react.js_d11fe7b62c27961c87ecd0f2490357b9.content
  exampleSite/resources/_gen/assets/js/scripts/syna-react.js_d11fe7b62c27961c87ecd0f2490357b9.json
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.content
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.json
  layouts/partials/fragments/list.html
  layouts/partials/fragments/toc.html
Labels: enhancement
