Repository okkur/syna, pull requests merged in 2018-07, with the labels that each got.

#217 Remove color switch for the title on member fragment in single mode
  layouts/partials/fragments/member.html
Labels: bug

#219 Add category support for content-single and content-split fragments
  exampleSite/config.toml
  exampleSite/content/article/content.md
  exampleSite/content/article/index.md
  layouts/partials/fragments/content-single.html
  layouts/partials/fragments/content-split.html
Labels: enhancement

#220 Add blog support
  exampleSite/config.toml
  exampleSite/content/blog/_index/index.md
  exampleSite/content/blog/article-1/index.md
  i18n/en.yaml
  layouts/_default/single.html
  layouts/partials/fragments/list.html
  static/contact.js
  static/hero.js
  static/main.js
Labels: enhancement

#230 Bump minimum Hugo version required by Syna
  theme.toml
Labels: bug

#232 Remove the icon container when there is no icon in items fragment
  layouts/partials/fragments/items.html
Labels: bug

#233 Add section header fragment
  exampleSite/content/_index/sample-custom-fragment.md
  exampleSite/content/_index/section-header.md
  layouts/partials/fragments/section-header.html
Labels: enhancement

#235 Merge two content fragments together
  exampleSite/content/about-split/content.md
  exampleSite/content/about/content.md
  exampleSite/content/article/content.md
  exampleSite/content/blog/article-1/index.md
  exampleSite/content/nesting/content.md
  layouts/partials/fragments/content-single.html
  layouts/partials/fragments/content.html
  layouts/partials/fragments/list.html
Labels: enhancement

#237 Make content sidebar alignment configurable
  exampleSite/content/about-split/content.md
  layouts/partials/fragments/content.html
Labels: enhancement

#238 Make table cell alignment more flexible and fix issues within it
  exampleSite/content/_index/table.md
  layouts/partials/fragments/table.html
Labels: enhancement

#241 Migrate 404 page from global to _global
  layouts/404.html
Labels: refactor

#240 Add documentation for the contact form fragment
  docs/fragments/README.md
  docs/fragments/contact.md
Labels: documentation

#244 Make naming consistent within contact fragment
  exampleSite/content/_index/contact.md
  layouts/partials/fragments/contact.html
Labels: enhancement

#245 Add installation guide
  README.md
  docs/README.md
Labels: documentation

#250 Fix table and item fragment icon urls
  exampleSite/content/_index/item_image-table-left.md
  layouts/partials/fragments/item.html
  layouts/partials/fragments/table.html
Labels: bug

#251 Fix 404 page logo alt text
  layouts/404.html
Labels: bug

#249 Fix button alignment in item fragment when there is an icon
  layouts/partials/fragments/item.html
Labels: bug

#252 Add documentation for favicon customization
  docs/README.md
Labels: documentation

#253 Change the url for theme attribution
  layouts/partials/fragments/copyright.html
Labels: bug

#254 Change behavior of fragment and children selection
  exampleSite/content/_index/items/index.md
  exampleSite/content/_index/single-member/index.md
  layouts/_default/single.html
  layouts/partials/fragments/items.html
  layouts/partials/fragments/member.html
  layouts/partials/fragments/portfolio.html
Labels: bug, enhancement

#255 Add registry for js files in fragments
  layouts/_default/single.html
  layouts/partials/fragments/contact.html
  layouts/partials/fragments/hero.html
  layouts/partials/fragments/portfolio.html
  layouts/partials/js.html
Labels: enhancement

#259 Refactor 404 layout
  exampleSite/content/_global/404.md
  layouts/404.html
  layouts/_default/single.html
  layouts/partials/fragments/404.html
  static/contact.js
  static/hero.js
  static/main.js
  static/portfolio.js
Labels: enhancement
