Repository okkur/syna, pull requests merged in 2018-06, with the labels that each got.

#158 Fix the problem causing the navbar to be hidden in bigger screen sizes
  layouts/partials/fragments/nav.html
  static-main/js/helpers/bootstrap-helper.js
  static-main/styles/syna.scss
  static/main.css
  static/main.js
Labels: bug

#130 Add Single Member Fragment
  exampleSite/content/index/portfolio.md
  exampleSite/content/index/portfolio/bio.md
  layouts/partials/fragments/member.html
Labels: enhancement

#162 Cleanup files
  exampleSite/config.toml
  exampleSite/content/about-split/content-split.md
  exampleSite/content/about/content.md
  exampleSite/content/about/footer.md
  exampleSite/content/global/footer.md
  exampleSite/content/index/awesome-team/donald.md
  exampleSite/content/index/awesome-team/ella.md
  exampleSite/content/index/awesome-team/gopher.md
  exampleSite/content/index/awesome-team/hector.md
  exampleSite/content/index/awesome-team/nancy.md
  exampleSite/content/index/awesome-team/yoda.md
  exampleSite/content/index/items/column1.md
  exampleSite/content/index/items/column2.md
  exampleSite/content/index/items/column3.md
  exampleSite/content/index/items_only/column-1.md
  exampleSite/content/index/items_only/column-2.md
  exampleSite/content/index/items_only/column-3.md
Labels: refactor

#173 Simplify fragments by using .Params without assignment
  layouts/_default/single.html
  layouts/partials/fragments/buttons.html
  layouts/partials/fragments/contact.html
  layouts/partials/fragments/content-single.html
  layouts/partials/fragments/content-split.html
  layouts/partials/fragments/copyright.html
  layouts/partials/fragments/embed.html
  layouts/partials/fragments/footer.html
  layouts/partials/fragments/hero.html
  layouts/partials/fragments/item.html
  layouts/partials/fragments/items.html
  layouts/partials/fragments/logos.html
  layouts/partials/fragments/member.html
  layouts/partials/fragments/nav.html
  layouts/partials/fragments/table.html
Labels: refactor

#180 Don't include hero.js script when particls is disabled
  layouts/partials/fragments/hero.html
Labels: bug

#177 Centralized fragment name generation
  layouts/_default/single.html
  layouts/partials/fragments/buttons.html
  layouts/partials/fragments/contact.html
  layouts/partials/fragments/content-single.html
  layouts/partials/fragments/content-split.html
  layouts/partials/fragments/copyright.html
  layouts/partials/fragments/embed.html
  layouts/partials/fragments/footer.html
  layouts/partials/fragments/hero.html
  layouts/partials/fragments/item.html
  layouts/partials/fragments/items.html
  layouts/partials/fragments/logos.html
  layouts/partials/fragments/member.html
  layouts/partials/fragments/nav.html
  layouts/partials/fragments/table.html
Labels: refactor

#176 Fix hidden contact fields
  layouts/partials/fragments/contact.html
Labels: bug

#174 Empty subs
  exampleSite/content/index/awesome-team/index.md
  exampleSite/content/index/items_only/index.md
  layouts/partials/fragments/items.html
  layouts/partials/fragments/member.html
Labels: bug

#181 Fix contact form js script
  static-main/js/contact.js
  static-main/js/helpers/jq-helpers.js
  static/contact.js
  static/main.js
Labels: bug

#142 Documentation/0 11
  CONTRIBUTING.md
  docs/README.md
  docs/fragments-01.png
Labels: documentation

#183 Rename all link variables to url to be more consistent
  exampleSite/content/about/footer.md
  exampleSite/content/about/hero.md
  exampleSite/content/dev/fallthrough/fragment/footer.md
  exampleSite/content/dev/fallthrough/fragment/logos/index.md
  exampleSite/content/dev/fallthrough/global/footer.md
  exampleSite/content/dev/fallthrough/global/logos.md
  exampleSite/content/dev/fallthrough/page/footer.md
  exampleSite/content/dev/fallthrough/page/logos.md
  exampleSite/content/global/footer.md
  exampleSite/content/index/awesome-team/ella.md
  exampleSite/content/index/awesome-team/gopher.md
  exampleSite/content/index/awesome-team/hector.md
  exampleSite/content/index/awesome-team/nancy.md
  exampleSite/content/index/awesome-team/yoda.md
  exampleSite/content/index/button_download.md
  exampleSite/content/index/buttons.md
  exampleSite/content/index/buttons_contribute.md
  exampleSite/content/index/hero/index.md
  exampleSite/content/index/item_button-center.md
  exampleSite/content/index/item_button-left.md
  exampleSite/content/index/item_button-right.md
  exampleSite/content/index/item_image-button-left.md
  exampleSite/content/index/item_image-table-left.md
  exampleSite/content/index/items/column1.md
  exampleSite/content/index/items/column2.md
  exampleSite/content/index/items/column3.md
  exampleSite/content/index/items_only/column-1.md
  exampleSite/content/index/items_only/column-2.md
  exampleSite/content/index/items_only/column-3.md
  exampleSite/content/index/logos.md
  exampleSite/content/index/logos_only.md
  exampleSite/content/index/portfolio/bio.md
  exampleSite/content/index/table.md
  layouts/partials/fragments/buttons.html
  layouts/partials/fragments/footer.html
  layouts/partials/fragments/hero.html
  layouts/partials/fragments/item.html
  layouts/partials/fragments/items.html
  layouts/partials/fragments/logos.html
  layouts/partials/fragments/member.html
  layouts/partials/fragments/table.html
Labels: refactor

#185 Add supported colors documentation
  docs/README.md
Labels: documentation

#184 Enable alert prompt for fragment with content not available
  exampleSite/content/dev/empty/index.md
  exampleSite/content/dev/empty/items.md
  exampleSite/content/dev/empty/member.md
  layouts/partials/fragments/items.html
  layouts/partials/fragments/member.html
Labels: enhancement

#190 Update the changelog with mpourismaiel changes
  CHANGELOG.md
Labels: documentation

#188 Iterate on documentation
  docs/README.md
Labels: documentation

#191 Add more entries in CHANGELOG
  CHANGELOG.md
Labels: documentation

#192 Change index and global path for less conflict
  docs/README.md
  docs/fragments-01.png
  exampleSite/content/_global/copyright.md
  exampleSite/content/_global/footer.md
  exampleSite/content/_global/index.md
  exampleSite/content/_global/nav.md
  exampleSite/content/_index/awesome-team/donald.md
  exampleSite/content/_index/awesome-team/ella.md
  exampleSite/content/_index/awesome-team/gopher.md
  exampleSite/content/_index/awesome-team/hector.md
  exampleSite/content/_index/awesome-team/index.md
  exampleSite/content/_index/awesome-team/nancy.md
  exampleSite/content/_index/awesome-team/yoda.md
  exampleSite/content/_index/button_download.md
  exampleSite/content/_index/buttons.md
  exampleSite/content/_index/buttons_contribute.md
  exampleSite/content/_index/contact.md
  exampleSite/content/_index/embed_subscribe.md
  exampleSite/content/_index/embed_video.md
  exampleSite/content/_index/header.jpg
  exampleSite/content/_index/hero/header.jpg
  exampleSite/content/_index/hero/index.md
  exampleSite/content/_index/hero/logo.svg
  exampleSite/content/_index/index.md
  exampleSite/content/_index/item_button-center.md
  exampleSite/content/_index/item_button-left.md
  exampleSite/content/_index/item_button-right.md
  exampleSite/content/_index/item_icon-center.md
  exampleSite/content/_index/item_icon-left.md
  exampleSite/content/_index/item_image-button-left.md
  exampleSite/content/_index/item_image-center.md
  exampleSite/content/_index/item_image-only.md
  exampleSite/content/_index/item_image-right.md
  exampleSite/content/_index/item_image-table-left.md
  exampleSite/content/_index/items.md
  exampleSite/content/_index/items/column1.md
  exampleSite/content/_index/items/column2.md
  exampleSite/content/_index/items/column3.md
  exampleSite/content/_index/items_only/column-1.md
  exampleSite/content/_index/items_only/column-2.md
  exampleSite/content/_index/items_only/column-3.md
  exampleSite/content/_index/items_only/index.md
  exampleSite/content/_index/logo.svg
  exampleSite/content/_index/logos.md
  exampleSite/content/_index/logos_only.md
  exampleSite/content/_index/portfolio.md
  exampleSite/content/_index/portfolio/bio.md
  exampleSite/content/_index/sample-custom-fragment.md
  exampleSite/content/_index/table.md
  layouts/_default/single.html
  layouts/partials/fragments/footer.html
  layouts/partials/fragments/hero.html
  layouts/partials/fragments/item.html
  layouts/partials/fragments/logos.html
  layouts/partials/fragments/member.html
  layouts/partials/fragments/nav.html
Labels: documentation, refactor

#204 Restructure single member mode
  layouts/partials/fragments/member.html
Labels: enhancement
