Repository okkur/syna, pull requests merged in 2018-08, with the labels that each got.

#265 Add support for pricing fragment
  exampleSite/content/about/pricing/index.md
  exampleSite/content/about/pricing/plan-1.md
  exampleSite/content/about/pricing/plan-2.md
  exampleSite/content/about/pricing/plan-3.md
  layouts/partials/fragments/pricing.html
  static-main/styles/_pricing.scss
  static-main/styles/index.scss
  static/main.css
Labels: enhancement

#274 Optimize images via optipng, jpegoptim and restructuring
  exampleSite/content/_index/header.jpg
  exampleSite/content/_index/hero/header.jpg
  exampleSite/content/_index/hero/logo.svg
  exampleSite/content/_index/logo.svg
  exampleSite/content/blog/article-2/screenshot.png
  exampleSite/static/images/bird-1.jpeg
  exampleSite/static/images/cat-1.jpeg
  exampleSite/static/images/cat-2.jpeg
  exampleSite/static/images/dog-1.jpeg
  exampleSite/static/images/dog-2.jpeg
  exampleSite/static/images/dog-3.jpeg
  exampleSite/static/images/header.jpg
  exampleSite/static/images/hugegopher.png
  exampleSite/static/images/screenshot.png
  exampleSite/static/images/tinygopher.png
Labels: refactor

#281 Fix issues with no image in portfolio and member fragments
  layouts/partials/fragments/member.html
  static-main/styles/_portfolio.scss
  static/syna-main.css
Labels: enhancement

#298 Fix default section in list fragment
  layouts/partials/fragments/list.html
Labels: bug

#299 Patch random issues
  exampleSite/content/_index/table.md
  exampleSite/content/fragments/item/index.md
  exampleSite/content/fragments/items/index.md
  exampleSite/content/fragments/portfolio/portfolio/bird-1.jpeg
  exampleSite/content/fragments/portfolio/portfolio/cat-1.jpeg
  exampleSite/content/fragments/portfolio/portfolio/cat-2.jpeg
  exampleSite/content/fragments/portfolio/portfolio/dog-1.jpeg
  exampleSite/content/fragments/portfolio/portfolio/dog-2.jpeg
  exampleSite/content/fragments/portfolio/portfolio/dog-3.jpeg
  exampleSite/content/fragments/pricing/code-pricing.md
  exampleSite/content/fragments/pricing/index.md
  exampleSite/content/fragments/pricing/pricing/index.md
  exampleSite/content/fragments/pricing/pricing/plan-1.md
  exampleSite/content/fragments/pricing/pricing/plan-2.md
  exampleSite/content/fragments/pricing/pricing/plan-3.md
  layouts/partials/fragments/portfolio.html
  layouts/partials/helpers/fragments.html
Labels: bug, enhancement

#302 Display an error message in portfolio when no item is available
  layouts/partials/fragments/portfolio.html
Labels: enhancement

#290 Add alignment variables for header fragment
  exampleSite/content/_index/header.md
  layouts/partials/fragments/header.html
Labels: enhancement

#303 Add ability to resize 404 image size
  exampleSite/content/_global/404.md
  layouts/partials/fragments/404.html
Labels: enhancement

#307 Add page and description for the 404 fragment
  exampleSite/content/_index/table.md
  exampleSite/content/fragments/404/404.png
  exampleSite/content/fragments/404/code-404.md
  exampleSite/content/fragments/404/index.md
Labels: documentation

#308 Remove extra header fragment in the index page
  exampleSite/content/_index/header.md
Labels: refactor

#309 Fix random issues
  exampleSite/content/dev/missing-images/footer.md
  exampleSite/content/dev/resource-fallthrough/fragment/footer/index.md
  exampleSite/content/dev/resource-fallthrough/global/footer/index.md
  exampleSite/content/dev/resource-fallthrough/page/footer/index.md
  exampleSite/content/dev/unconfigured-images/footer.md
  exampleSite/content/fragments/footer/code-footer-example.md
  exampleSite/content/fragments/footer/footer-example.md
  layouts/partials/fragments/footer.html
Labels: bug, enhancement

#310 Change all relative url pipes to relLangURL
  layouts/partials/custom/css.html
  layouts/partials/custom/js.html
  layouts/partials/fragments/contact.html
  layouts/partials/fragments/editor.html
  layouts/partials/fragments/hero.html
  layouts/partials/fragments/list.html
  layouts/partials/fragments/portfolio.html
  layouts/partials/fragments/react-portal.html
  layouts/partials/head.html
  layouts/partials/helpers/image.html
  layouts/partials/js.html
Labels: enhancement

#311 Fix list fragment content check and add list page for dev section
  exampleSite/content/dev/_index.md
  exampleSite/content/dev/_index/index.md
  exampleSite/content/dev/_index/list.md
  exampleSite/content/dev/empty-subitems/index.md
  exampleSite/content/dev/missing-images/index.md
  exampleSite/content/dev/resource-fallthrough/_index.md
  exampleSite/content/dev/resource-fallthrough/_index/index.md
  exampleSite/content/dev/resource-fallthrough/_index/list.md
  exampleSite/content/dev/resource-fallthrough/fragment/index.md
  exampleSite/content/dev/resource-fallthrough/global/index.md
  exampleSite/content/dev/resource-fallthrough/page/index.md
  exampleSite/content/dev/unconfigured-images/index.md
  exampleSite/content/fragments/_index/list.md
  layouts/partials/fragments/list.html
  layouts/partials/helpers/fragments.html
Labels: bug, enhancement

#287 Add tiled layout to list fragment
  exampleSite/content/blog/_index/list.md
  exampleSite/content/fragments/_index/list.md
  layouts/partials/fragments/list.html
Labels: enhancement

#318 Replace table fragment with list fragment
  exampleSite/content/_index/list.md
  exampleSite/content/_index/table.md
  exampleSite/content/fragments/404/index.md
  exampleSite/content/fragments/contact/index.md
  exampleSite/content/fragments/content/index.md
  exampleSite/content/fragments/copyright/index.md
  exampleSite/content/fragments/editor/index.md
  exampleSite/content/fragments/embed/index.md
  exampleSite/content/fragments/header/index.md
  exampleSite/content/fragments/hero/index.md
  exampleSite/content/fragments/item/index.md
  exampleSite/content/fragments/items/index.md
  exampleSite/content/fragments/logos/index.md
  exampleSite/content/fragments/member/index.md
  exampleSite/content/fragments/nav/index.md
  exampleSite/content/fragments/portfolio/index.md
  exampleSite/content/fragments/react-portal/index.md
  exampleSite/content/fragments/table/index.md
Labels: refactor

#317 Extract warning message for not configured subitems
  layouts/partials/fragments/items.html
  layouts/partials/fragments/member.html
  layouts/partials/fragments/portfolio.html
  layouts/partials/helpers/empty-subpath.html
Labels: refactor

#320 Extract table into a helper from table and item fragment
  layouts/partials/fragments/item.html
  layouts/partials/fragments/table.html
  layouts/partials/helpers/table.html
Labels: enhancement, refactor
