Repository okkur/syna, pull requests merged in 2018-05, with the labels that each got.

#113 Fix scroll-to-top bgcolor
  layouts/partials/nav.html
  static-main/styles/syna.scss
  static/main.css
Labels: bug

#118 Refactor layouts and make content fragments
  exampleSite/content/about-split/content-split.md
  exampleSite/content/about-split/index.md
  exampleSite/content/about/content.md
  exampleSite/content/about/footer.md
  exampleSite/content/about/index.md
  exampleSite/content/nesting/content.md
  exampleSite/content/nesting/index.md
  layouts/_default/single.html
  layouts/_default/split.html
  layouts/partials/fragments/content-single.html
  layouts/partials/fragments/content-split.html
  layouts/partials/fragments/hero.html
Labels: enhancement

#122 Update bootstrap and fix color overwrite
  exampleSite/config.toml
  exampleSite/static/css/_variables.scss
  exampleSite/static/css/overwrite-color.css
  exampleSite/static/css/overwrite-color.css.map
  exampleSite/static/css/overwrite-color.min.css
  exampleSite/static/css/overwrite-color.min.css.map
  exampleSite/static/css/overwrite-reboot.css
  exampleSite/static/css/overwrite-reboot.css.map
  exampleSite/static/css/overwrite-reboot.min.css
  exampleSite/static/css/overwrite-reboot.min.css.map
  package.json
  static-main/styles/bootstrap-overwrite/_variables.scss
  static-main/styles/bootstrap-overwrite/mixins/_alert.scss
  static-main/styles/bootstrap-overwrite/mixins/_background-variant.scss
  static-main/styles/bootstrap-overwrite/mixins/_badge.scss
  static-main/styles/bootstrap-overwrite/mixins/_border-radius.scss
  static-main/styles/bootstrap-overwrite/mixins/_box-shadow.scss
  static-main/styles/bootstrap-overwrite/mixins/_breakpoints.scss
  static-main/styles/bootstrap-overwrite/mixins/_buttons.scss
  static-main/styles/bootstrap-overwrite/mixins/_caret.scss
  static-main/styles/bootstrap-overwrite/mixins/_clearfix.scss
  static-main/styles/bootstrap-overwrite/mixins/_float.scss
  static-main/styles/bootstrap-overwrite/mixins/_forms.scss
  static-main/styles/bootstrap-overwrite/mixins/_gradients.scss
  static-main/styles/bootstrap-overwrite/mixins/_grid-framework.scss
  static-main/styles/bootstrap-overwrite/mixins/_grid.scss
  static-main/styles/bootstrap-overwrite/mixins/_hover.scss
  static-main/styles/bootstrap-overwrite/mixins/_image.scss
  static-main/styles/bootstrap-overwrite/mixins/_list-group.scss
  static-main/styles/bootstrap-overwrite/mixins/_lists.scss
  static-main/styles/bootstrap-overwrite/mixins/_nav-divider.scss
  static-main/styles/bootstrap-overwrite/mixins/_navbar-align.scss
  static-main/styles/bootstrap-overwrite/mixins/_pagination.scss
  static-main/styles/bootstrap-overwrite/mixins/_reset-text.scss
  static-main/styles/bootstrap-overwrite/mixins/_resize.scss
  static-main/styles/bootstrap-overwrite/mixins/_screen-reader.scss
  static-main/styles/bootstrap-overwrite/mixins/_size.scss
  static-main/styles/bootstrap-overwrite/mixins/_table-row.scss
  static-main/styles/bootstrap-overwrite/mixins/_text-emphasis.scss
  static-main/styles/bootstrap-overwrite/mixins/_text-hide.scss
  static-main/styles/bootstrap-overwrite/mixins/_text-truncate.scss
  static-main/styles/bootstrap-overwrite/mixins/_transition.scss
  static-main/styles/bootstrap-overwrite/mixins/_visibility.scss
  static-main/styles/bootstrap-overwrite/overwrite-color.scss
  static-main/styles/bootstrap-overwrite/utilities/_align.scss
  static-main/styles/bootstrap-overwrite/utilities/_background.scss
  static-main/styles/bootstrap-overwrite/utilities/_borders.scss
  static-main/styles/bootstrap-overwrite/utilities/_clearfix.scss
  static-main/styles/bootstrap-overwrite/utilities/_display.scss
  static-main/styles/bootstrap-overwrite/utilities/_embed.scss
  static-main/styles/bootstrap-overwrite/utilities/_flex.scss
  static-main/styles/bootstrap-overwrite/utilities/_float.scss
  static-main/styles/bootstrap-overwrite/utilities/_position.scss
  static-main/styles/bootstrap-overwrite/utilities/_screenreaders.scss
  static-main/styles/bootstrap-overwrite/utilities/_sizing.scss
  static-main/styles/bootstrap-overwrite/utilities/_spacing.scss
  static-main/styles/bootstrap-overwrite/utilities/_text.scss
  static-main/styles/bootstrap-overwrite/utilities/_visibility.scss
  static/main.css
  yarn.lock
Labels: bug

#147 Remove extra whitespace in layout files
  exampleSite/layouts/partials/fragments/sample-custom-fragment.html
  layouts/_default/baseof.html
  layouts/_default/single.html
  layouts/partials/custom/css.html
  layouts/partials/custom/js.html
  layouts/partials/fragments/buttons.html
  layouts/partials/fragments/contact.html
  layouts/partials/fragments/content-single.html
  layouts/partials/fragments/content-split.html
  layouts/partials/fragments/copyright.html
  layouts/partials/fragments/embed.html
  layouts/partials/fragments/footer.html
  layouts/partials/fragments/hero.html
  layouts/partials/fragments/item.html
  layouts/partials/fragments/items.html
  layouts/partials/fragments/logos.html
  layouts/partials/fragments/member.html
  layouts/partials/fragments/nav.html
  layouts/partials/fragments/table.html
  layouts/partials/head.html
  layouts/partials/js.html
Labels: enhancement

#150 Remove unused contact.disable config from exampleSite config
  exampleSite/config.toml
Labels: refactor

#149 Add fontawesome to local dependencies and remove cdn
  config/webpack.js
  layouts/partials/head.html
  package.json
  static-main/styles/index.scss
  static/main.css
  static/static/fa-brands-400.eot
  static/static/fa-brands-400.svg
  static/static/fa-brands-400.ttf
  static/static/fa-brands-400.woff
  static/static/fa-brands-400.woff2
  static/static/fa-regular-400.svg
  static/static/fa-solid-900.eot
  static/static/fa-solid-900.svg
  static/static/fa-solid-900.ttf
  static/static/fa-solid-900.woff
  static/static/fa-solid-900.woff2
  yarn.lock
Labels: enhancement

#154 Fix position of copyright message in mobile
  layouts/partials/fragments/copyright.html
Labels: bug

#155 Patch font path and bootstrap navbar toggler
  config/webpack.js
  layouts/partials/fragments/nav.html
  static-main/js/helpers/bootstrap-helper.js
  static-main/js/index.js
  static-main/styles/syna.scss
  static/fonts/fa-brands-400.eot
  static/fonts/fa-brands-400.svg
  static/fonts/fa-brands-400.ttf
  static/fonts/fa-brands-400.woff
  static/fonts/fa-brands-400.woff2
  static/fonts/fa-regular-400.svg
  static/fonts/fa-solid-900.eot
  static/fonts/fa-solid-900.svg
  static/fonts/fa-solid-900.ttf
  static/fonts/fa-solid-900.woff
  static/fonts/fa-solid-900.woff2
  static/main.css
  static/main.js
Labels: bug
