Repository okkur/syna, pull requests merged in 2019-04, with the labels that each got.

#549 Document events, stripe and add events to pricing and contact fragments
  exampleSite/content/dev/alignments/stripe/stripe-center.md
  exampleSite/content/dev/alignments/stripe/stripe-left.md
  exampleSite/content/dev/alignments/stripe/stripe-multi-price-center.md
  exampleSite/content/dev/alignments/stripe/stripe-multi-price-left.md
  exampleSite/content/dev/alignments/stripe/stripe-multi-price-right.md
  exampleSite/content/dev/alignments/stripe/stripe-only-editable-center.md
  exampleSite/content/dev/alignments/stripe/stripe-only-editable-left.md
  exampleSite/content/dev/alignments/stripe/stripe-only-editable-right.md
  exampleSite/content/dev/alignments/stripe/stripe-right.md
  exampleSite/content/dev/colors/stripe/stripe-dark.md
  exampleSite/content/dev/colors/stripe/stripe-light.md
  exampleSite/content/dev/colors/stripe/stripe-multi-price-dark.md
  exampleSite/content/dev/colors/stripe/stripe-multi-price-light.md
  exampleSite/content/dev/colors/stripe/stripe-multi-price-primary.md
  exampleSite/content/dev/colors/stripe/stripe-multi-price-secondary.md
  exampleSite/content/dev/colors/stripe/stripe-multi-price-white.md
  exampleSite/content/dev/colors/stripe/stripe-only-editable-dark.md
  exampleSite/content/dev/colors/stripe/stripe-only-editable-light.md
  exampleSite/content/dev/colors/stripe/stripe-only-editable-primary.md
  exampleSite/content/dev/colors/stripe/stripe-only-editable-secondary.md
  exampleSite/content/dev/colors/stripe/stripe-only-editable-white.md
  exampleSite/content/dev/colors/stripe/stripe-primary.md
  exampleSite/content/dev/colors/stripe/stripe-secondary.md
  exampleSite/content/dev/colors/stripe/stripe-white.md
  exampleSite/content/dev/events/payment/stripe.md
  exampleSite/content/docs/events/content.md
  exampleSite/content/docs/events/index.md
  exampleSite/content/fragments/contact/docs.md
  exampleSite/content/fragments/pricing/docs.md
  exampleSite/content/fragments/stripe/code-stripe-multi-price.md
  exampleSite/content/fragments/stripe/code-stripe-only-editable.md
  exampleSite/content/fragments/stripe/code-stripe.md
  exampleSite/content/fragments/stripe/docs.md
  exampleSite/content/fragments/stripe/stripe-multi-price.md
  exampleSite/content/fragments/stripe/stripe-only-editable.md
  exampleSite/content/fragments/stripe/stripe.md
  layouts/partials/fragments/stripe.html
Labels: documentation

#550 Add plan:change subscriber to pricing fragment
  assets/js/pricing.js
  assets/scripts/syna-pricing.js
  exampleSite/resources/_gen/assets/js/scripts/syna-pricing.js_d11fe7b62c27961c87ecd0f2490357b9.content
  exampleSite/resources/_gen/assets/js/scripts/syna-pricing.js_d11fe7b62c27961c87ecd0f2490357b9.json
  layouts/partials/fragments/pricing.html
  webpack.config.js
Labels: enhancement

#555 Fix Stripe's event subscriber not working when there are more than one stripe fragments on the page
  assets/js/stripe.js
  assets/scripts/syna-stripe.js
  layouts/partials/fragments/stripe.html
  layouts/partials/js.html
Labels: bug

#557 Enable preventDefault by making event cancelable
  assets/js/contact.js
Labels: bug
