Repository okkur/syna, pull requests merged in 2019-12, with the labels that each got.

#637 Remove stray end tag div and indent block
  layouts/_default/baseof.html
Labels: bug

#627 Add classes to some of the fragments elements
  layouts/partials/fragments/content.html
  layouts/partials/fragments/copyright.html
  layouts/partials/fragments/hero.html
  layouts/partials/fragments/nav.html
  layouts/partials/helpers/categories.html
  layouts/partials/helpers/publish-date.html
  layouts/partials/helpers/section-header.html
Labels: enhancement

#643 Move modal html template to js asset files
  assets/js/modal.js
  assets/js/templates/modal.js
  assets/scripts/syna-main.js
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.content
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.json
  layouts/_default/baseof.html
Labels: refactor

#644 Upgrade bootstrap to 4.4.1
  assets/styles/bootstrap/_badge.scss
  assets/styles/bootstrap/_breadcrumb.scss
  assets/styles/bootstrap/_button-group.scss
  assets/styles/bootstrap/_buttons.scss
  assets/styles/bootstrap/_card.scss
  assets/styles/bootstrap/_carousel.scss
  assets/styles/bootstrap/_close.scss
  assets/styles/bootstrap/_code.scss
  assets/styles/bootstrap/_custom-forms.scss
  assets/styles/bootstrap/_dropdown.scss
  assets/styles/bootstrap/_forms.scss
  assets/styles/bootstrap/_functions.scss
  assets/styles/bootstrap/_grid.scss
  assets/styles/bootstrap/_images.scss
  assets/styles/bootstrap/_input-group.scss
  assets/styles/bootstrap/_list-group.scss
  assets/styles/bootstrap/_mixins.scss
  assets/styles/bootstrap/_modal.scss
  assets/styles/bootstrap/_nav.scss
  assets/styles/bootstrap/_navbar.scss
  assets/styles/bootstrap/_pagination.scss
  assets/styles/bootstrap/_popover.scss
  assets/styles/bootstrap/_print.scss
  assets/styles/bootstrap/_progress.scss
  assets/styles/bootstrap/_reboot.scss
  assets/styles/bootstrap/_root.scss
  assets/styles/bootstrap/_tables.scss
  assets/styles/bootstrap/_type.scss
  assets/styles/bootstrap/_variables.scss
  assets/styles/bootstrap/bootstrap-grid.scss
  assets/styles/bootstrap/bootstrap-reboot.scss
  assets/styles/bootstrap/bootstrap.scss
  assets/styles/bootstrap/mixins/_background-variant.scss
  assets/styles/bootstrap/mixins/_badge.scss
  assets/styles/bootstrap/mixins/_buttons.scss
  assets/styles/bootstrap/mixins/_caret.scss
  assets/styles/bootstrap/mixins/_float.scss
  assets/styles/bootstrap/mixins/_forms.scss
  assets/styles/bootstrap/mixins/_grid-framework.scss
  assets/styles/bootstrap/mixins/_grid.scss
  assets/styles/bootstrap/mixins/_hover.scss
  assets/styles/bootstrap/mixins/_image.scss
  assets/styles/bootstrap/mixins/_list-group.scss
  assets/styles/bootstrap/mixins/_lists.scss
  assets/styles/bootstrap/mixins/_nav-divider.scss
  assets/styles/bootstrap/mixins/_reset-text.scss
  assets/styles/bootstrap/mixins/_screen-reader.scss
  assets/styles/bootstrap/mixins/_table-row.scss
  assets/styles/bootstrap/mixins/_text-emphasis.scss
  assets/styles/bootstrap/utilities/_background.scss
  assets/styles/bootstrap/utilities/_text.scss
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.content
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.json
  package.json
  yarn.lock
Labels: enhancement

#645 Add unsafe markdown configuration
  exampleSite/config-dev.toml
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.content
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.json
Labels: deps_hugo

#628 Add first tests
  .gitignore
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/fragment-structure.spec.js
  cypress/integration/list.spec.js
  cypress/integration/navbar.spec.js
  cypress/integration/resource-fallthrough.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  exampleSite/layouts/partials/fragments/sample-custom-fragment.html
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.content
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.json
  package.json
  yarn.lock
Labels: enhancement

#647 Add cypress github actions workflow
  .github/workflows/cypress.yml
Labels: enhancement

#666 Add more tests
  cypress/fixtures/contact.json
  cypress/fixtures/example.json
  cypress/integration/events.js
  cypress/integration/form-errors.spec.js
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.content
  exampleSite/resources/_gen/assets/scss/styles/index.scss_a4e369375f17bb89f2019364cbe7a830.json
Labels: enhancement

#665 Add default section and container class to container helper
  layouts/partials/helpers/container.html
Labels: bug

#669 Fix sort order of list fragment
  layouts/partials/helpers/list-pages.html
Labels: bug

#670 Add default page title
  layouts/partials/fragments/list.html
  layouts/partials/head.html
  layouts/partials/helpers/page-title.html
Labels: enhancement
